Libdrm 2.4.110
pop-os/libdrm pull request #2
Opened 2022-03-31 20:34 UTC by jackpot51

Required for https://github.com/pop-os/mesa/pull/7

2022-04-02 00:23 UTC, XV-02 approved these changes
This looks good to go, and nothing anomalous presented itself with this present.

2022-04-02 00:36 UTC, XV-02 requested changes
I got a little too excited. I need to check this on Focal still. Disregard my approval.

2022-04-04 17:55 UTC, XV-02 approved these changes
Everything looks good, and there are no evident signs of regression in anything I've looked at. Good to go.

2022-04-04 17:57 UTC, crawfxrd approved these changes

2022-04-04 17:57 UTC, merged